# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://CaseyBennington.github.io" # the base hostname & protocol for your site
# MEDIUM_INTEGRATION_TOKEN: 25d2c9980643d6141afee9de07b8d0de9da2013901b5cefca6262f45dd888ff9a
# MEDIUM_USER_ID: 171322253a2c311cae6bcb7d74ac375f904e0e713c9cd64e84ba71a48bab859e7

# THEME-SPECIFIC CONFIGURATION
theme-settings:
  # Meta
  title: Casey Bennington # Your name will go here
  description: '\<coder\> - one who creates cool stuff' # used by search engines
  owner: Casey Bennington
  first_published: 2016
  email: cbenning@vt.edu

  # Header and footer text
  header_text: >
     <h1>Casey Bennington</h1>
     <p>I'm a problem solver specializing in the RoR and MEAN stacks.</p>
  header_text_feature_image: banner.jpg
  footer_text: >
    <p>&copy; CaseyBennington.com. 2016 Powered by <a href="http://jekyllrb.com">Jekyll</a>.</p>

  # Icons
  social:
    rss: false
    email_address: cbenning@vt.edu # Full email address, e.g. "sam@example.com"
    # behance:
    # bitbucket:
    # dribbble:
    facebook: casey.bennington
    # flickr:
    github: CaseyBennington # github profile name, e.g. "madebymunsters"
    google_plus: +CaseyBennington
    # instagram:
    linkedin: https://www.linkedin.com/in/caseybennington # Full URL
    # pinterest:
    # reddit:
    # soundcloud:
    # stack_exchange:  # Full URL
    # steam:
    # tumblr:
    twitter: BenningtonCasey
    # wordpress: cbenning@vt.edu
    # youtube:

  # Scripts
  google_analytics: "UA-79355854-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: caseybennington
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 6
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate, jekyll-crosspost-to-medium]
